// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudAssuredWorkloadsV1
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc

func sample(
  client: AssuredWorkloadsServiceClient, organizationId: String, locationId: String,
  workloadId: String
) async throws {
  let response = try await client.getWorkload(
    request: GetWorkloadRequest()
      .with {
        $0.name = "organizations/\(organizationId)/locations/\(locationId)/workloads/\(workloadId)"
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudAssuredWorkloadsV1.AssuredWorkloadsServiceClient()
      try await sample(
        client: client, organizationId: "[placeholder]", locationId: "[placeholder]",
        workloadId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
