// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol AssuredWorkloadsServiceStub: Sendable {
    func createWorkload(
      request: CreateWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateWorkload(
      request: UpdateWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredWorkloadsV1.Workload

    func restrictAllowedResources(
      request: RestrictAllowedResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredWorkloadsV1.RestrictAllowedResourcesResponse

    func deleteWorkload(
      request: DeleteWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getWorkload(
      request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredWorkloadsV1.Workload

    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredWorkloadsV1.ListWorkloadsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
