// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AssuredWorkloadsServiceLogging: AssuredWorkloadsServiceStub {
    let inner: any AssuredWorkloadsServiceStub
    let logger: Logger

    public init(_ inner: any AssuredWorkloadsServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudAssuredworkloadsV1"
      logger[metadataKey: "gcp.client.service"] = "assuredworkloads"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AssuredWorkloadsService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createWorkload(
      request: CreateWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createWorkload",
        action: {
          (r: CreateWorkloadRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createWorkload(request: r, options: o)
        })
    }

    public func updateWorkload(
      request: UpdateWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredworkloadsV1.Workload {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateWorkload",
        action: {
          (r: UpdateWorkloadRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssuredworkloadsV1.Workload
          in
          return try await self.inner.updateWorkload(request: r, options: o)
        })
    }

    public func restrictAllowedResources(
      request: RestrictAllowedResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredworkloadsV1.RestrictAllowedResourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "restrictAllowedResources",
        action: {
          (r: RestrictAllowedResourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssuredworkloadsV1.RestrictAllowedResourcesResponse
          in
          return try await self.inner.restrictAllowedResources(request: r, options: o)
        })
    }

    public func deleteWorkload(
      request: DeleteWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteWorkload",
        action: {
          (r: DeleteWorkloadRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteWorkload(request: r, options: o)
        })
    }

    public func getWorkload(
      request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredworkloadsV1.Workload {
      try await self._intercept(
        request: request,
        options: options,
        name: "getWorkload",
        action: {
          (r: GetWorkloadRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssuredworkloadsV1.Workload
          in
          return try await self.inner.getWorkload(request: r, options: o)
        })
    }

    public func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssuredworkloadsV1.ListWorkloadsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listWorkloads",
        action: {
          (r: ListWorkloadsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssuredworkloadsV1.ListWorkloadsResponse
          in
          return try await self.inner.listWorkloads(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
