// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request for fetching violations in an organization.
public struct ListViolationsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Workload name.
  /// Format `organizations/{org_id}/locations/{location}/workloads/{workload}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. Specifies the time window for retrieving active Violations.
  /// When specified, retrieves Violations that were active between start_time
  /// and end_time.
  public var interval: TimeWindow? = nil

  /// Optional. Page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Page token returned from previous request.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A custom filter for filtering by the Violations properties.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListViolationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListViolationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.assuredworkloads.v1.ListViolationsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
