// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Workload object for managing highly regulated workloads of cloud
/// customers.
public struct Workload: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The resource name of the workload.
  /// Format:
  /// organizations/{organization}/locations/{location}/workloads/{workload}
  ///
  /// Read-only.
  public var name: Swift.String = Swift.String()

  /// Required. The user-assigned display name of the Workload.
  /// When present it must be between 4 to 30 characters.
  /// Allowed characters are: lowercase and uppercase letters, numbers,
  /// hyphen, and spaces.
  ///
  /// Example: My Workload
  public var displayName: Swift.String = Swift.String()

  /// Output only. The resources associated with this workload.
  /// These resources will be created when creating the workload.
  /// If any of the projects already exist, the workload creation will fail.
  /// Always read only.
  public var resources: [Workload.ResourceInfo] = []

  /// Required. Immutable. Compliance Regime associated with this workload.
  public var complianceRegime: Workload.ComplianceRegime = Workload.ComplianceRegime()

  /// Output only. Immutable. The Workload creation timestamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The billing account used for the resources which are
  /// direct children of workload. This billing account is initially associated
  /// with the resources created as part of Workload creation.
  /// After the initial creation of these resources, the customer can change
  /// the assigned billing account.
  /// The resource name has the form
  /// `billingAccounts/{billing_account_id}`. For example,
  /// `billingAccounts/012345-567890-ABCDEF`.
  public var billingAccount: Swift.String = Swift.String()

  /// Optional. ETag of the workload, it is calculated on the basis
  /// of the Workload contents. It will be used in Update & Delete operations.
  public var etag: Swift.String = Swift.String()

  /// Optional. Labels applied to the workload.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Input only. The parent resource for the resources managed by this Assured Workload. May
  /// be either empty or a folder resource which is a child of the
  /// Workload parent. If not specified all resources are created under the
  /// parent organization.
  /// Format:
  /// folders/{folder_id}
  public var provisionedResourcesParent: Swift.String = Swift.String()

  /// Input only. Settings used to create a CMEK crypto key. When set, a project with a KMS
  /// CMEK key is provisioned.
  /// This field is deprecated as of Feb 28, 2022.
  /// In order to create a Keyring, callers should specify,
  /// ENCRYPTION_KEYS_PROJECT or KEYRING in ResourceSettings.resource_type field.
  @available(*, deprecated)
  public var kmsSettings: Workload.KMSSettings? = nil

  /// Input only. Resource properties that are used to customize workload resources.
  /// These properties (such as custom project id) will be used to create
  /// workload resources if possible. This field is optional.
  public var resourceSettings: [Workload.ResourceSettings] = []

  /// Output only. Represents the KAJ enrollment state of the given workload.
  public var kajEnrollmentState: Workload.KajEnrollmentState = Workload.KajEnrollmentState()

  /// Optional. Indicates the sovereignty status of the given workload.
  /// Currently meant to be used by Europe/Canada customers.
  public var enableSovereignControls: Swift.Bool = Swift.Bool()

  /// Output only. Represents the SAA enrollment response of the given workload.
  /// SAA enrollment response is queried during GetWorkload call.
  /// In failure cases, user friendly error message is shown in SAA details page.
  public var saaEnrollmentResponse: Workload.SaaEnrollmentResponse? = nil

  /// Output only. Urls for services which are compliant for this Assured Workload, but which
  /// are currently disallowed by the ResourceUsageRestriction org policy.
  /// Invoke RestrictAllowedResources endpoint to allow your project developers
  /// to use these services in their environment."
  public var compliantButDisallowedServices: [Swift.String] = []

  /// Optional. Compliance Regime associated with this workload.
  public var partner: Workload.Partner = Workload.Partner()

  /// Initialize a new instance of `Workload`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Workload().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represent the resources that are children of this Workload.
  public struct ResourceInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Resource identifier.
    /// For a project this represents project_number.
    public var resourceId: Swift.Int64 = Swift.Int64()

    /// Indicates the type of resource.
    public var resourceType: Workload.ResourceInfo.ResourceType = Workload.ResourceInfo
      .ResourceType()

    /// Initialize a new instance of `ResourceInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceInfo().with { $0.resourceId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The type of resource.
    public enum ResourceType: Codable, Equatable, Sendable {
      /// Unknown resource type.
      case unspecified
      /// Consumer project.
      /// AssuredWorkloads Projects are no longer supported. This field will be
      /// ignored only in CreateWorkload requests. ListWorkloads and GetWorkload
      /// will continue to provide projects information.
      /// Use CONSUMER_FOLDER instead.
      @available(*, deprecated)
      case consumerProject
      /// Consumer project containing encryption keys.
      case encryptionKeysProject
      /// Keyring resource that hosts encryption keys.
      case keyring
      /// Consumer Folder.
      case consumerFolder
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .consumerProject: return 1
        case .encryptionKeysProject: return 2
        case .keyring: return 3
        case .consumerFolder: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "RESOURCE_TYPE_UNSPECIFIED"
        case .consumerProject: return "CONSUMER_PROJECT"
        case .encryptionKeysProject: return "ENCRYPTION_KEYS_PROJECT"
        case .keyring: return "KEYRING"
        case .consumerFolder: return "CONSUMER_FOLDER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "RESOURCE_TYPE_UNSPECIFIED": self = .unspecified
        case "CONSUMER_PROJECT": self = .consumerProject
        case "CONSUMER_FOLDER": self = .consumerFolder
        case "ENCRYPTION_KEYS_PROJECT": self = .encryptionKeysProject
        case "KEYRING": self = .keyring
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .consumerProject
        case 2: self = .encryptionKeysProject
        case 3: self = .keyring
        case 4: self = .consumerFolder
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .consumerProject: return try container.encode(1)
        case .encryptionKeysProject: return try container.encode(2)
        case .keyring: return try container.encode(3)
        case .consumerFolder: return try container.encode(4)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.assuredworkloads.v1.Workload.ResourceInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Settings specific to the Key Management Service.
  /// This message is deprecated.
  /// In order to create a Keyring, callers should specify,
  /// ENCRYPTION_KEYS_PROJECT or KEYRING in ResourceSettings.resource_type field.
  @available(*, deprecated)
  public struct KMSSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Input only. Immutable. The time at which the Key Management Service will automatically create a
    /// new version of the crypto key and mark it as the primary.
    public var nextRotationTime: GoogleCloudWkt.Timestamp? = nil

    /// Required. Input only. Immutable. [next_rotation_time] will be advanced by this period when the Key
    /// Management Service automatically rotates a key. Must be at least 24 hours
    /// and at most 876,000 hours.
    public var rotationPeriod: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `KMSSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KMSSettings().with { $0.nextRotationTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.assuredworkloads.v1.Workload.KMSSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Represent the custom settings for the resources to be created.
  public struct ResourceSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Resource identifier.
    /// For a project this represents project_id. If the project is already
    /// taken, the workload creation will fail.
    /// For KeyRing, this represents the keyring_id.
    /// For a folder, don't set this value as folder_id is assigned by Google.
    public var resourceId: Swift.String = Swift.String()

    /// Indicates the type of resource. This field should be specified to
    /// correspond the id to the right resource type (CONSUMER_FOLDER or
    /// ENCRYPTION_KEYS_PROJECT)
    public var resourceType: Workload.ResourceInfo.ResourceType = Workload.ResourceInfo
      .ResourceType()

    /// User-assigned resource display name.
    /// If not empty it will be used to create a resource with the specified
    /// name.
    public var displayName: Swift.String = Swift.String()

    /// Initialize a new instance of `ResourceSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceSettings().with { $0.resourceId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.assuredworkloads.v1.Workload.ResourceSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Signed Access Approvals (SAA) enrollment response.
  public struct SaaEnrollmentResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Indicates SAA enrollment status of a given workload.
    public var setupStatus: Workload.SaaEnrollmentResponse.SetupState? = nil

    /// Indicates SAA enrollment setup error if any.
    public var setupErrors: [Workload.SaaEnrollmentResponse.SetupError] = []

    /// Initialize a new instance of `SaaEnrollmentResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SaaEnrollmentResponse().with { $0.setupStatus = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Setup state of SAA enrollment.
    public enum SetupState: Codable, Equatable, Sendable {
      /// Unspecified.
      case unspecified
      /// SAA enrollment pending.
      case statusPending
      /// SAA enrollment comopleted.
      case statusComplete
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .statusPending: return 1
        case .statusComplete: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SETUP_STATE_UNSPECIFIED"
        case .statusPending: return "STATUS_PENDING"
        case .statusComplete: return "STATUS_COMPLETE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SETUP_STATE_UNSPECIFIED": self = .unspecified
        case "STATUS_PENDING": self = .statusPending
        case "STATUS_COMPLETE": self = .statusComplete
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .statusPending
        case 2: self = .statusComplete
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .statusPending: return try container.encode(1)
        case .statusComplete: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Setup error of SAA enrollment.
    public enum SetupError: Codable, Equatable, Sendable {
      /// Unspecified.
      case unspecified
      /// Invalid states for all customers, to be redirected to AA UI for
      /// additional details.
      case errorInvalidBaseSetup
      /// Returned when there is not an EKM key configured.
      case errorMissingExternalSigningKey
      /// Returned when there are no enrolled services or the customer is
      /// enrolled in CAA only for a subset of services.
      case errorNotAllServicesEnrolled
      /// Returned when exception was encountered during evaluation of other
      /// criteria.
      case errorSetupCheckFailed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .errorInvalidBaseSetup: return 1
        case .errorMissingExternalSigningKey: return 2
        case .errorNotAllServicesEnrolled: return 3
        case .errorSetupCheckFailed: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SETUP_ERROR_UNSPECIFIED"
        case .errorInvalidBaseSetup: return "ERROR_INVALID_BASE_SETUP"
        case .errorMissingExternalSigningKey: return "ERROR_MISSING_EXTERNAL_SIGNING_KEY"
        case .errorNotAllServicesEnrolled: return "ERROR_NOT_ALL_SERVICES_ENROLLED"
        case .errorSetupCheckFailed: return "ERROR_SETUP_CHECK_FAILED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SETUP_ERROR_UNSPECIFIED": self = .unspecified
        case "ERROR_INVALID_BASE_SETUP": self = .errorInvalidBaseSetup
        case "ERROR_MISSING_EXTERNAL_SIGNING_KEY": self = .errorMissingExternalSigningKey
        case "ERROR_NOT_ALL_SERVICES_ENROLLED": self = .errorNotAllServicesEnrolled
        case "ERROR_SETUP_CHECK_FAILED": self = .errorSetupCheckFailed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .errorInvalidBaseSetup
        case 2: self = .errorMissingExternalSigningKey
        case 3: self = .errorNotAllServicesEnrolled
        case 4: self = .errorSetupCheckFailed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .errorInvalidBaseSetup: return try container.encode(1)
        case .errorMissingExternalSigningKey: return try container.encode(2)
        case .errorNotAllServicesEnrolled: return try container.encode(3)
        case .errorSetupCheckFailed: return try container.encode(4)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.assuredworkloads.v1.Workload.SaaEnrollmentResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Supported Compliance Regimes.
  public enum ComplianceRegime: Codable, Equatable, Sendable {
    /// Unknown compliance regime.
    case unspecified
    /// Information protection as per DoD IL4 requirements.
    case il4
    /// Criminal Justice Information Services (CJIS) Security policies.
    case cjis
    /// FedRAMP High data protection controls
    case fedrampHigh
    /// FedRAMP Moderate data protection controls
    case fedrampModerate
    /// Assured Workloads For US Regions data protection controls
    case usRegionalAccess
    /// Health Insurance Portability and Accountability Act controls
    case hipaa
    /// Health Information Trust Alliance controls
    case hitrust
    /// Assured Workloads For EU Regions and Support controls
    case euRegionsAndSupport
    /// Assured Workloads For Canada Regions and Support controls
    case caRegionsAndSupport
    /// International Traffic in Arms Regulations
    case itar
    /// Assured Workloads for Australia Regions and Support controls
    /// Available for public preview consumption.
    /// Don't create production workloads.
    case auRegionsAndUsSupport
    /// Assured Workloads for Partners
    case assuredWorkloadsForPartners
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .il4: return 1
      case .cjis: return 2
      case .fedrampHigh: return 3
      case .fedrampModerate: return 4
      case .usRegionalAccess: return 5
      case .hipaa: return 6
      case .hitrust: return 7
      case .euRegionsAndSupport: return 8
      case .caRegionsAndSupport: return 9
      case .itar: return 10
      case .auRegionsAndUsSupport: return 11
      case .assuredWorkloadsForPartners: return 12
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMPLIANCE_REGIME_UNSPECIFIED"
      case .il4: return "IL4"
      case .cjis: return "CJIS"
      case .fedrampHigh: return "FEDRAMP_HIGH"
      case .fedrampModerate: return "FEDRAMP_MODERATE"
      case .usRegionalAccess: return "US_REGIONAL_ACCESS"
      case .hipaa: return "HIPAA"
      case .hitrust: return "HITRUST"
      case .euRegionsAndSupport: return "EU_REGIONS_AND_SUPPORT"
      case .caRegionsAndSupport: return "CA_REGIONS_AND_SUPPORT"
      case .itar: return "ITAR"
      case .auRegionsAndUsSupport: return "AU_REGIONS_AND_US_SUPPORT"
      case .assuredWorkloadsForPartners: return "ASSURED_WORKLOADS_FOR_PARTNERS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMPLIANCE_REGIME_UNSPECIFIED": self = .unspecified
      case "IL4": self = .il4
      case "CJIS": self = .cjis
      case "FEDRAMP_HIGH": self = .fedrampHigh
      case "FEDRAMP_MODERATE": self = .fedrampModerate
      case "US_REGIONAL_ACCESS": self = .usRegionalAccess
      case "HIPAA": self = .hipaa
      case "HITRUST": self = .hitrust
      case "EU_REGIONS_AND_SUPPORT": self = .euRegionsAndSupport
      case "CA_REGIONS_AND_SUPPORT": self = .caRegionsAndSupport
      case "ITAR": self = .itar
      case "AU_REGIONS_AND_US_SUPPORT": self = .auRegionsAndUsSupport
      case "ASSURED_WORKLOADS_FOR_PARTNERS": self = .assuredWorkloadsForPartners
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .il4
      case 2: self = .cjis
      case 3: self = .fedrampHigh
      case 4: self = .fedrampModerate
      case 5: self = .usRegionalAccess
      case 6: self = .hipaa
      case 7: self = .hitrust
      case 8: self = .euRegionsAndSupport
      case 9: self = .caRegionsAndSupport
      case 10: self = .itar
      case 11: self = .auRegionsAndUsSupport
      case 12: self = .assuredWorkloadsForPartners
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .il4: return try container.encode(1)
      case .cjis: return try container.encode(2)
      case .fedrampHigh: return try container.encode(3)
      case .fedrampModerate: return try container.encode(4)
      case .usRegionalAccess: return try container.encode(5)
      case .hipaa: return try container.encode(6)
      case .hitrust: return try container.encode(7)
      case .euRegionsAndSupport: return try container.encode(8)
      case .caRegionsAndSupport: return try container.encode(9)
      case .itar: return try container.encode(10)
      case .auRegionsAndUsSupport: return try container.encode(11)
      case .assuredWorkloadsForPartners: return try container.encode(12)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Key Access Justifications(KAJ) Enrollment State.
  public enum KajEnrollmentState: Codable, Equatable, Sendable {
    /// Default State for KAJ Enrollment.
    case unspecified
    /// Pending State for KAJ Enrollment.
    case pending
    /// Complete State for KAJ Enrollment.
    case complete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .complete: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "KAJ_ENROLLMENT_STATE_UNSPECIFIED"
      case .pending: return "KAJ_ENROLLMENT_STATE_PENDING"
      case .complete: return "KAJ_ENROLLMENT_STATE_COMPLETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "KAJ_ENROLLMENT_STATE_UNSPECIFIED": self = .unspecified
      case "KAJ_ENROLLMENT_STATE_PENDING": self = .pending
      case "KAJ_ENROLLMENT_STATE_COMPLETE": self = .complete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .complete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .complete: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Supported Assured Workloads Partners.
  public enum Partner: Codable, Equatable, Sendable {
    /// Unknown partner regime/controls.
    case unspecified
    /// S3NS regime/controls.
    case localControlsByS3Ns
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .localControlsByS3Ns: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PARTNER_UNSPECIFIED"
      case .localControlsByS3Ns: return "LOCAL_CONTROLS_BY_S3NS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PARTNER_UNSPECIFIED": self = .unspecified
      case "LOCAL_CONTROLS_BY_S3NS": self = .localControlsByS3Ns
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .localControlsByS3Ns
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .localControlsByS3Ns: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.assuredworkloads.v1.Workload"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
